import type {Area,Movement,ProblemSolver}from'../types';
export type Operator={name:string;home:Area;start:Area;current:Area};export type ShiftState={startedAt:string;operators:Operator[];movements:Movement[];problemSolvers:ProblemSolver[]};
const nameKey=(name:string)=>name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\s+/g,' ').trim();
export function createShift(assignments:{name:string;area:Area}[],problemSolvers:ProblemSolver[]=[]):ShiftState{const seen=new Set<string>();const operators=assignments.filter(x=>{const key=nameKey(x.name);if(seen.has(key))return false;seen.add(key);return true}).map(x=>({name:x.name.trim(),home:x.area,start:x.area,current:x.area}));return{startedAt:new Date().toISOString(),operators,movements:[],problemSolvers}}
export function addOperatorToShift(state:ShiftState,name:string,area:Area):ShiftState{if(state.operators.some(operator=>nameKey(operator.name)===nameKey(name)))return state;return{...state,operators:[...state.operators,{name:name.trim(),home:area,start:area,current:area}]}}
export function moveOperator(state:ShiftState,name:string,to:Area,at=new Date().toISOString()):ShiftState{const key=nameKey(name),op=state.operators.find(x=>nameKey(x.name)===key);if(!op||op.current===to)return state;const from=op.current;return{...state,operators:state.operators.map(x=>nameKey(x.name)===key?{...x,current:to}:x),movements:[...state.movements,{person:op.name,from,to,at}]}}
export function moveOperators(state:ShiftState,names:string[],to:Area,at=new Date().toISOString()):ShiftState{const selected=new Set(names.map(nameKey));return state.operators.reduce((current,operator)=>selected.has(nameKey(operator.name))?moveOperator(current,operator.name,to,at):current,state)}
export function movedOnly(s:ShiftState){return s.operators.filter(x=>x.current!==x.start)}
export function areaCounts(s:ShiftState){return s.operators.reduce<Record<string,number>>((a,x)=>(a[x.current]=(a[x.current]||0)+1,a),{})}
export function returnToStart(s:ShiftState,name:string){const op=s.operators.find(x=>x.name===name);return op?moveOperator(s,name,op.start):s}
export function returnOperatorsToStart(state:ShiftState,names:string[],at=new Date().toISOString()):ShiftState{const selected=new Set(names.map(nameKey));return state.operators.reduce((current,operator)=>selected.has(nameKey(operator.name))?moveOperator(current,operator.name,operator.start,at):current,state)}
